### ISSUE TITLE
Weight Editor Doesn't Properly Weigh Newly Added Bones

### ISSUE THREAD

**Issue by KingJigglypuff** [libertyernie/brawltools#103]
I wanted to do a bit of a custom rig on an existing model, but I don't want to import into 3DS Max (Normals break), do the quick rig, re-export, re-import into BB, and re-apply materials, so I thought I could use BB's Weight Editor to bypass this, but there's a bit of an issue. The Weight Editor doesn't seem to like newly added bones.

I made a test bone and weighed a vertice, but this ends up happening every time.
http://i.imgur.com/FpdYdo8.png

Saving doesn't fix it, either.
http://i.imgur.com/Nk1p3Er.png

Is there anything that can be done about this?

**Comment by BlackJax96** [comment]
Hi KJP. I've pushed a fix that should remedy this issue.

For future reference, if you want to create a bone on-the-fly within the model viewer, you can click an existing bone, hold alt, and transform the bone like you normally would, and it will create a new child bone automatically.

However, after this is done, or after you add a new bone the traditional way outside of the model viewer, you will have to check "Update Mesh Bind Pose" and "Move Bone Only" in the CHR0 editor so that the vertex doesn't seem to fly away as soon as you start weighing it to that bone. Experiment with those two checkboxes checked and unchecked in different combinations and you'll see why they're necessary in this instance.

Let me know if there's anything still wrong.

**Comment by KingJigglypuff** [comment]
Thanks for letting me know about this (never knew about holding Alt over a bone to make a new one in the model viewer).

Though regardless of the Update Mesh Bind Pose and Move Bone Only options being checked, I still get the flying vertices issue, so I think I'll wait for Hotfix 2 to come out for v0.78.
